describe('addPerm-la-e2ejourney-mobile ',()=>{
        const num = Date.now();
        const n = num.toString();

    it(`ipad-mini - LA Journey - Validate mobile version`,function(){
        cy.viewport(`ipad-mini`)
        cy.visit('/')
        cy.startPage()
        
        cy.stubLogin('dfeAdmin')
        cy.mobileMenu()
        cy.welcomePage('Dfe Admin User')
        cy.mobileMenu()
        cy.addPermissions()
        cy.mobileMenu()
        cy.typeOfUserPage('la')
        cy.mobileMenu()
        cy.typeOfUserLA('1')
        cy.mobileMenu()
        cy.laWhichLA('redbridge')
        cy.mobileMenu()
        cy.email(n +'+abcdef@def.com')
        cy.mobileMenu()
        cy.fullName(n + '+John Paul Smith')
        cy.mobileMenu()
        cy.checkAnswerPage()
        cy.mobileMenu()
        cy.confirmationPage(n + '+John Paul Smith')
    })
    it('iphone - LA Journey - Validate mobile version',()=>{
        cy.clearCookies()
        cy.viewport(`iphone-x`)
        
        cy.visit('/')
        cy.startPage()
        cy.stubLogin('dfeAdmin')
        cy.mobileMenu()
        cy.welcomePage('Dfe Admin User')
        cy.mobileMenu()
        cy.addPermissions()
        cy.mobileMenu()
        cy.typeOfUserPage('la')
        cy.mobileMenu()
        cy.typeOfUserLA('1')
        cy.mobileMenu()
        cy.laWhichLA('redbridge')
        cy.mobileMenu()
        cy.email(n +'-abcdef@def.com')
        cy.mobileMenu()
        cy.fullName(n + '-John Paul Smith')
        cy.mobileMenu()
        cy.checkAnswerPage()
        cy.mobileMenu()
        cy.confirmationPage(n + '-John Paul Smith')

    })
    it('samsung-s10 - LA Journey - Validate mobile version',()=>{
        cy.clearCookies()
        cy.viewport(`samsung-s10`) 
        cy.visit('/')
        cy.startPage()
        cy.stubLogin('dfeAdmin')
        cy.mobileMenu()
        cy.welcomePage('Dfe Admin User')
        cy.mobileMenu()
        cy.addPermissions()
        cy.mobileMenu()
        cy.typeOfUserPage('la')
        cy.mobileMenu()
        cy.typeOfUserLA('1')
        cy.mobileMenu()
        cy.laWhichLA('redbridge')
        cy.mobileMenu()
        cy.email(n +'abcdef@def.com')
        cy.mobileMenu()
        cy.fullName(n + 'John Paul Smith')
        cy.mobileMenu()
        cy.checkAnswerPage()
        cy.mobileMenu()
        cy.confirmationPage(n + 'John Paul Smith')

    })
})