describe("| addPerm-la-checkAnswerPage | FHG-3911 LA manager - add permissions - check account details page", { tags: ['LAMan'] }, () => {
     beforeEach(()=> {
		cy.visit('/')
        	cy.integrationLogin('vcsman')
       
	})
    
    it('AC1 - add a service name and validate content',()=>{
        cy.visit('/')
        cy.visit('/ServiceWizzard/ServiceName')
        cy.contains('h1', 'What is the name of the service?');
        cy.get('#service-name')
        cy.get('#service-name')
            .should('be.visible')
            .click()
            .clear()
            .type('Cypress Test Service')
        cy.get('[data-testid="name-continue-button"]')
            .contains('Continue')
            .should('be.visible')
            .click()

        cy.contains('legend', 'What support does the service offer?')
        cy.get('[data-testid="activities,clubsandgroups"]').check();
        cy.get('[data-testid="activities"]').check();
        cy.get('[data-testid="button-continue"]')
            .contains('Continue')
            .should('be.visible')
            .click()

        cy.contains('h1', 'Can children or young people use the service?')
        cy.get('[data-testid="yes-select"]').check()
        cy.get('[data-testid="age-min"]').select('1 year old')
        cy.get('[data-testid="age-max"]').select('10 years old')
        cy.get('[data-testid="button-continue"]')
            .contains('Continue')
            .should('be.visible')
            .click()

        cy.contains('h2', 'Which language is the service offered in?')
        cy.get('[data-testid="language-select"]').select('English')
        cy.get('[data-testid="button-continue"]')
            .contains('Continue')
            .should('be.visible')
            .click()

        cy.contains('h1', 'Does the service cost money to use?')
        cy.get('#pay-service').check()
        cy.get('#Cost')
            .should('be.visible')
            .click()
            .clear()
            .type('2.50')
        cy.get('#cost-unit').check()
        cy.get('[data-testid="button-continue"]')
            .contains('Continue')
            .should('be.visible')
            .click()

        cy.contains('legend', 'Does this service take place on set days and times?')
        cy.get('#HastimesChoice').check()
        cy.contains('button', 'Continue')
            .should('be.visible')
            .click()


        cy.contains('legend', 'When does this service take place?')
        cy.contains('span', 'Which days does the service take place?')
        cy.get('#monday').check()
        cy.get('#tuesday').check()
        cy.contains('button', 'Continue')
            .should('be.visible')
            .click()

        cy.contains('legend', 'When this service takes place')
        cy.contains('span', 'Does the service take place at the same time on each of those days?')
        cy.get('[data-testid="yes-select"]').check()
        cy.contains('button', 'Continue')
            .should('be.visible')
            .click()

        cy.contains('legend', 'What times does this service take place?')
        cy.get('#OpeningHours_0__Starts')
            .should('be.visible')
            .click()
            .clear()
            .type('10')
        cy.get('#OpeningHours_0__Finishes')
            .should('be.visible')
            .click()
            .clear()
            .type('4')
        cy.get('#OpeningHours_0__FinishesTimeOfDay').select('pm')
        cy.contains('button', 'Continue')
            .should('be.visible')
            .click()


        cy.contains('h1', 'How can families use the service?')
        cy.get('#inperson').check()
        cy.contains('button', 'Continue')
            .should('be.visible')
            .click()

        cy.contains('legend', 'Address')
        cy.contains('h2', 'What is the address?')
        cy.get('#Address1')
            .should('be.visible')
            .click()
            .clear()
            .type('Address Line 1')
        cy.get('#Address2')
            .should('be.visible')
            .click()
            .clear()
            .type('Address Line 2')
        cy.get('#City')
            .should('be.visible')
            .click()
            .clear()
            .type('City')
        cy.get('#StateProvince')
            .should('be.visible')
            .click()
            .clear()
            .type('County')
        cy.get('#PostalCode')
            .should('be.visible')
            .click()
            .clear()
            .type('B38 9RW')
        cy.contains('button', 'Continue')
            .should('be.visible')
            .click()


        cy.contains('legend', 'How can people contact the service?')
        cy.get('#ContactSelectionEmail').check()
        cy.get('#ContactSelectionTelephone').check()
        cy.get('#ContactSelectionWebsite').check()
        cy.get('#ContactSelectionTextMessage').check()
        cy.get('#contact-by-email')
            .should('be.visible')
            .click()
            .clear()
            .type('cypress-service@email.com')
        cy.get('#contact-by-phone')
            .should('be.visible')
            .click()
            .clear()
            .type('0712345678')
        cy.get('#contact-by-website')
            .should('be.visible')
            .click()
            .clear()
            .type('www.cypress-service-test.com')
        cy.get('#contact-by-text')
            .should('be.visible')
            .click()
            .clear()
            .type('0712345678')
        cy.contains('button', 'Continue')
            .should('be.visible')
            .click()

        //cy.contains('h1', 'How can people contact the service?')
        //cy.contains('h1', 'What do you want to add?')
        cy.get('#with-hint')
            .should('be.visible')
            .click()
            .clear()
            .type('Is able to help many families')
        cy.contains('button', 'Continue')
            .should('be.visible')
            .click()
    })
    
})